version: '3.9'

x-env_file: &env_file
  env_file: ./env/.dev.env

services:

  db:
    image: postgres:13.13
    environment:
      # POSTGRES_DB: ${POSTGRES_DB}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "recordex"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432

    # <<: *env_file
